---
abstract: 'Turn markdown into phpBB code'
author:
  - 'Paul Fenwick <pjf@cpan.org>'
build_requires: {}
configure_requires:
  ExtUtils::MakeMaker: 6.30
dynamic_config: 0
generated_by: 'Dist::Zilla version 4.300039, CPAN::Meta::Converter version 2.120921'
license: perl
meta-spec:
  url: http://module-build.sourceforge.net/META-spec-v1.4.html
  version: 1.4
name: Markdown-phpBB
requires:
  Data::Dumper: 0
  Markdent::Parser: 0
  Markdent::Role::Handler: 0
  Moose: 0
  autodie: 0
  perl: 5.010
  strict: 0
  warnings: 0
resources:
  repository: git://github.com/pjf/Markdown-phpBB
version: 0.02
